# Generated by Django 3.2.23 on 2024-01-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=10)),
                ('asset_type', models.CharField(choices=[('1', 'currency'), ('2', 'cryptocurrency')], default='1', max_length=1)),
            ],
        ),
    ]
