# Generated by Django 3.2.23 on 2024-01-12 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 12, 13, 31, 36, 891918, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
